SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE Apexsql_data_Diff_MonthO
AS
  SELECT DATEADD([M] , -2 , CONVERT(DATE , GETDATE())), CONVERT(DATE , GETDATE());
  SELECT DATEADD([hh] , 1 , GETDATE())
GO;
GO
